SELECT
  COUNT(DISTINCT CASE WHEN name = 'visited' THEN session_id END) AS users,
  COUNT(DISTINCT CASE WHEN name = 'opened' THEN session_id END) AS outbound_users,
  COUNT(DISTINCT CASE WHEN name = 'opened' THEN session_id || ':' || tool END) AS outbound_choices,
  COUNT(DISTINCT CASE WHEN name = 'returned' THEN session_id END) AS returned,
  COUNT(DISTINCT CASE WHEN name = 'visited' AND occurred_on >= date('now', '-6 days') THEN session_id END) AS users_7d,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND occurred_on >= date('now', '-6 days') THEN session_id END) AS outbound_users_7d,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'album-relay' THEN session_id END) AS album_relay,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'creator-inbox' THEN session_id END) AS creator_inbox,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'profile-palette' THEN session_id END) AS profile_palette,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'tag-loom' THEN session_id END) AS tag_loom,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'date-quilt' THEN session_id END) AS date_quilt,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'mimi-deck' THEN session_id END) AS mimi_deck,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'fedi-route' THEN session_id END) AS fedi_route,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'peta-sheet' THEN session_id END) AS peta_sheet,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'kuru-list' THEN session_id END) AS kuru_list,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'kata-prompt' THEN session_id END) AS kata_prompt,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'hataraku-tile' THEN session_id END) AS hataraku_tile,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'algo-lane' THEN session_id END) AS algo_lane,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'mingle-frame' THEN session_id END) AS mingle_frame,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'sky-dial' THEN session_id END) AS sky_dial,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'tango-orbit' THEN session_id END) AS tango_orbit,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'ava-rack' THEN session_id END) AS ava_rack,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'chair-call' THEN session_id END) AS chair_call,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'dice-seat' THEN session_id END) AS dice_seat,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'yose-bloom' THEN session_id END) AS yose_bloom,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'heart-board' THEN session_id END) AS heart_board,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'yoru-mado' THEN session_id END) AS yoru_mado,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'kasane-fuda' THEN session_id END) AS kasane_fuda,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'maigo-poster' THEN session_id END) AS maigo_poster,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'yomiato' THEN session_id END) AS yomiato,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'uchigraph' THEN session_id END) AS uchigraph,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'tsumi-erabi' THEN session_id END) AS tsumi_erabi,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'ipass-map' THEN session_id END) AS ipass_map,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'takufuda' THEN session_id END) AS takufuda,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'tabidan' THEN session_id END) AS tabidan,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'yorishiru' THEN session_id END) AS yorishiru,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'mcp-erabi' THEN session_id END) AS mcp_erabi,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'tegotae' THEN session_id END) AS tegotae,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'otayori-maku' THEN session_id END) AS otayori_maku,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'noriai-hyo' THEN session_id END) AS noriai_hyo,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'kairan-to' THEN session_id END) AS kairan_to,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'site-hodoki' THEN session_id END) AS site_hodoki,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'pon-hakushu' THEN session_id END) AS pon_hakushu,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'ano-hon-fuda' THEN session_id END) AS ano_hon_fuda,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'post-gura' THEN session_id END) AS post_gura,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'suketto-court' THEN session_id END) AS suketto_court,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'round-fuda' THEN session_id END) AS round_fuda,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'tejun-dai' THEN session_id END) AS tejun_dai,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'aikagi-ban' THEN session_id END) AS aikagi_ban,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'seibi-to' THEN session_id END) AS seibi_to,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'choka-to' THEN session_id END) AS choka_to,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'tsukue-no-hi' THEN session_id END) AS tsukue_no_hi,
  COUNT(DISTINCT CASE WHEN name = 'opened' AND tool = 'shiori-dana' THEN session_id END) AS shiori_dana
FROM product_events;
